---
Standards:
  - Title: Getting Ready
    Description: Preparing for Ada
    UID: 0218ee5b-5f7a-4d29-b786-55637e416911
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: d225025a-5ba3-464b-a669-3bb165924e32
        Path: /00-preparing-for-ada/00-starter.md
      -
        Type: Lesson
        UID: f5a99ab6-c687-4706-aceb-eaeb5e5c59b0
        Path: /00-preparing-for-ada/01-installfest.md
      -
        Type: Resource
        UID: cb2c97c0-9534-4025-b23b-a2a6c980afe0
        Path: /00-preparing-for-ada/installfest/installfest-intel.resource.md
      -
        Type: Resource
        UID: 2b18bb5b-5f59-4c43-bced-bae7f44307c1
        Path: /00-preparing-for-ada/installfest/installfest-m1.resource.md
      -
        Type: Lesson
        UID: a3a851b4-a725-4e6b-acd1-96d948a90d21
        Path: /00-preparing-for-ada/02-workflow.md
      -
        Type: Checkpoint
        UID: d5884ace-2cf9-46e5-b279-29ef1a501cbb
        Path: /00-preparing-for-ada/preparing-for-ada.checkpoint.md
  - Title: Coding Snowman
    Description: Practice with Python
    UID: 93a229d0-2bf8-48ca-a0f7-9a72a0a323b3
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: b4385d80-5e21-4934-a031-1c66e8605c01
        Path: /00-preparing-for-ada/dictionaries.md