---
Standards:
  - Title: Getting Ready
    Description: Preparing for Ada
    UID: 0218ee5b-5f7a-4d29-b786-55637e416911
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a0dcfc49-d7ae-4d85-8f83-22ebb7982872
        Path: /00-preparing-for-ada/00-starter.md
      -
        Type: Lesson
        UID: f5a99ab6-c687-4706-aceb-eaeb5e5c59b0
        Path: /00-preparing-for-ada/01-installfest.md
      -
        Type: Resource
        UID: cb2c97c0-9534-4025-b23b-a2a6c980afe0
        Path: /00-preparing-for-ada/installfest/installfest-intel.resource.md
      -
        Type: Resource
        UID: 2b18bb5b-5f59-4c43-bced-bae7f44307c1
        Path: /00-preparing-for-ada/installfest/installfest-m1.resource.md
      -
        Type: Lesson
        UID: a3a851b4-a725-4e6b-acd1-96d948a90d21
        Path: /00-preparing-for-ada/02-workflow.md
      - 
        Type: Lesson
        UID: 7ff13769-cfc8-42f6-b550-1a0b8a8e4933
        Path: /00-preparing-for-ada/02-python-style.md          
      -
        Type: Checkpoint
        UID: d5884ace-2cf9-46e5-b279-29ef1a501cbb
        Path: /00-preparing-for-ada/preparing-for-ada.checkpoint.md
  - Title: Coding Guess the Number and Snowman
    Description: Practice with Python
    UID: 93a229d0-2bf8-48ca-a0f7-9a72a0a323b3
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a63942ea-ef3e-43bd-aa69-cecba91a3845
        Path: /01-intro-to-python/00-variables-and-io.md
      -
        Type: Lesson
        UID: 36f31874-6a19-4257-a94e-0e1319032a11
        Path: /01-intro-to-python/01-conditionals.md
      -
        Type: Lesson
        UID: 78485f2f-da36-4cea-95ca-9019b7a32e13
        Path: /01-intro-to-python/02-functions.md        
      -
        Type: Lesson
        UID: e6128aa7-9956-4588-8492-40a3d01772b0
        Path: /01-intro-to-python/03-loops.md
      -
        Type: Lesson
        UID: 0089a87e-1c65-4b67-9c0a-55e4213610d5
        Path: /01-intro-to-python/04-lists.md
      -
        Type: Lesson
        UID: b4385d80-5e21-4934-a031-1c66e8605c01
        Path: /01-intro-to-python/05-dictionaries.md
      -
        Type: Checkpoint
        UID: f732de97-d800-482f-8f2c-8fb88e9e34b6
        Path: /01-intro-to-python/06-snowman.checkpoint.md
  
      - 
        Type: Resource
        UID: 4ba8f29d-fa11-4a26-8b9b-be5be478c5d1
        Path: /01-intro-to-python/resources/game-loop.md
      - 
        Type: Resource
        UID: 8b5cb812-02ae-488f-9fa7-9c4ca82a3e45
        Path: /01-intro-to-python/resources/src/04-lists/game-list.py

